### ISSUE TITLE
Way to make 2.2 Ghz available and effects

### ISSUE THREAD

**Issue by Pesach85** [nofearnohappy/kernel_6.0_hermes#12]
First of all sorry for unproper use of issue section, because i want to suggest already a solution.

Instead of change the dvfs table for cpu_level_1 is better to make the script detect the CPU_LEVEL_2 for just a reason: all other related script of PLL and temperature are activated as programmed for that frequence.
I was experimenting some overheat, cpu costantly at 48-50°. With this solution you can feel the back of the smartphone cooler.

Plus this gives a little boost in benchmark, tried 2 times the test to be sure: 
Before:
![screenshot_20161102-200901](https://cloud.githubusercontent.com/assets/2959385/19948236/d845d0e6-a14b-11e6-8fa2-88c5713159a3.png)
After:
![screenshot_20161102-213152](https://cloud.githubusercontent.com/assets/2959385/19948237/d86ae41c-a14b-11e6-9fd1-dfb840098097.png)

The commit is registered here: 

https://github.com/Pesach85/kernel_6.0_hermes/commit/ea515206114eb3a066627d08e50d00008629a755

**Comment by andrea2107** [comment]
Nice commit,i added it to my 3.10.104 kernel,when i finish testing( it compiled succesfully yay) i will give you credits :)
