### ISSUE TITLE
Question about imgsensor commit

### ISSUE THREAD

**Issue by pgeorgef** [nofearnohappy/kernel_6.0_hermes#18]
What have you modified in the rom to make it work alright and no rotated? I've tried to copy the libcam libs from your aosp with this commit in it but I just got a bootloop without any specific reasons in logcat

**Comment by nofearnohappy** [comment]
https://github.com/nofearnohappy/kernel_6.0_hermes/blob/master/kernel-3.10/drivers/misc/mediatek/imgsensor/src/mt6795/s5k3m2_mipi_raw/s5k3m2mipi_Sensor.c#L225

**Comment by nofearnohappy** [comment]
search by sensor (.mirror )

**Comment by nofearnohappy** [comment]
the last kernel on my gita corresponds rom to https://yadi.sk/d/3B8Dfd5S3Ne5j5

**Comment by nofearnohappy** [comment]
if you do not load the case MB and not in this

**Comment by pgeorgef** [comment]
Do you still have the sources for this rom https://yadi.sk/d/3B8Dfd5S3Ne5j5 ?

**Comment by nofearnohappy** [comment]
yes

**Comment by nofearnohappy** [comment]
https://drive.google.com/file/d/0B10jrZzpoiVKQm1pZnp5R3FWVFk/view?usp=sharing

**Comment by pgeorgef** [comment]
Thanks
